apiVersion: v1
kind: ConfigMap
metadata:
  name: biblioteca-config
data:
  CORS_ORIGINS: "https://bibliotechu.duckdns.org,http://bibliotechu.duckdns.org"
  OPENROUTER_REFERER: "https://bibliotechu.duckdns.org"
