apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biblioteca-backend
spec:
  rules:
    - host: api.biblioteca.example.com
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 5132
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 5132
          - path: /api/roles
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 5132
          - path: /api/demo
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 5132
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 5132
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 5132
          - path: /api/catalog
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 3002
          - path: /api/chatbot
            pathType: Prefix
            backend:
              service:
                name: chatbot-service
                port:
                  number: 3003
