apiVersion: v1
kind: ConfigMap
metadata:
  name: biblioteca-config
  labels:
    app.kubernetes.io/part-of: biblioteca-u
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5132"
  CORS_ORIGINS: "https://bibliotechu.duckdns.org"

  POSTGRES_DB: "catalog_db"
  POSTGRES_USER: "biblioadmin"
  DB_HOST: "pg-biblioteca-edu-alex25.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "catalog_db"
  DB_USER: "biblioadmin"
  DB_SSL: "true"

  AUTH_SERVICE_URL: "http://identity-service:5132"
  CATALOG_SERVICE_URL: "http://catalog-service:3002"

  AI_PROVIDER: "huggingface"
  HF_MODEL: "facebook/bart-large-mnli"
  CHAT_PROVIDER: "gemini"
  CHATBOT_PROVIDER: "gemini"
  GEMINI_MODEL: "gemini-2.5-flash"
  GROQ_MODEL: "llama-3.1-8b-instant"
  OPENROUTER_MODEL: "mistralai/mistral-7b-instruct:free"
  OPENROUTER_REFERER: "https://bibliotechu.duckdns.org"
  OPENROUTER_TITLE: "Biblioteca U"

  RABBITMQ_URL: ""
  CHATBOT_STREAM_NAME: "chatbot_events"
  CHATBOT_STREAM_GROUP: "chatbot_logger"
  AZURE_SERVICE_BUS_QUEUE: "library-logging-queue"
