apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: biblioteca

resources:
  - namespace.yaml
  - configmap.yaml
  - identity-service.yaml
  - catalog-service.yaml
  - chatbot-service.yaml
  - ingress.yaml
